### ISSUE TITLE
Firmware incompatibilities

### ISSUE THREAD

**Issue by oliver-walker-hms** [hms-networks/sc-flexy-tag-info-lib#23]
Firmware 13.3 has the wrong hardcoded index for tag type. Off by 1 index.
Works fine in newer firmware.

**Comment by TomKimsey** [comment]
Is this an issue or something just just needs to be documented in the readme?

**Comment by oliver-walker-hms** [comment]
I think documenting this in the readme would be enough

**Comment by TomKimsey** [comment]
Its pretty much a blanket statement we can add to all the repos. Only 14.0+.
